name: Run Kubernetes Job
author: Phan Thanh upgraded from Brent Pendergraft
description: 'Runs a Kubernetes Job and reports the output to stdout'
inputs:
  kubeconfig-file:
    description: 'base64 encoding of the kubectl config file (usually at ~/.kube/config)'
    required: false
  image:
    description: 'Name of the docker image in a remote repository (i.e. "debian")'
    required: true
  namespace:
    description: 'Kubernetes namespace where the job will run'
    required: true

runs:
  using: docker
  image: Dockerfile

branding:
  icon: zap
  color: gray-dark